---
info:
  title: ble_gw_dm_attributes
attributes:
  - name: bluetooth_address
    required: true
    schema:
      minLength: 12
      maxLength: 12
      type: string
    x-ctype: string
    x-broadcast: false
    x-default: "0"
    x-example: "010203040506"
    x-prepare: false
    x-readable: true
    x-savable: false
    x-writable: false
    summary: Bluetooth address
  - name: dm_cnx_delay
    required: true
    schema:
      type: integer
      minimum: 0
      maximum: 600
    x-ctype: uint16_t
    x-broadcast: true
    x-default: 0
    x-prepare: false
    x-readable: true
    x-savable: true
    x-writable: true
    x-validator: cp16
    summary: "Delay (in seconds) before connecting to DM server"
    description: "Write: Control point - Write 0 to generate new randomized delay with value between (mdm_cnx_delay_minin, dm_cnx_delay_max). Read: time in seconds to delay before connecting."
  - name: dm_cnx_delay_min
    required: true
    schema:
      type: integer
      minimum: 1
      maximum: 599
    x-ctype: uint16_t
    x-broadcast: true
    x-default: 1
    x-prepare: false
    x-readable: true
    x-savable: true
    x-writable: true
    summary: "Min delay (in seconds) before connecting to DM server."
  - name: dm_cnx_delay_max
    required: true
    schema:
      type: integer
      minimum: 2
      maximum: 600
    x-ctype: uint16_t
    x-broadcast: true
    x-default: 300
    x-prepare: false
    x-readable: true
    x-savable: true
    x-writable: true
    summary: "Max delay (in seconds) before connecting to DM server."
  - name: factory_load_path
    required: true
    schema:
      maxLength: 32
      minLength: 1
      type: string
    x-ctype: string
    x-broadcast: false
    x-default: /lfs1/enc/factory_load.txt
    x-prepare: false
    x-readable: true
    x-savable: true
    x-writable: true
    summary: "Path for factory settings that can be restored with attribute load"
  - name: device_id
    required: true
    schema:
      maxLength: 64
      minLength: 0
      type: string
    x-ctype: string
    x-broadcast: true
    x-default: ""
    x-prepare: false
    x-readable: true
    x-savable: true
    x-writable: true
    summary: "Unique identifier for the device. When firmware boots, if the value is blank (the default value), the firmware will set a unique value for the device using BLE MAC address, IMEI, or some similar value."
  - name: smp_auth_req
    required: true
    schema:
      maximum: 1
      minimum: 0
      type: integer
    x-ctype: bool
    x-broadcast: true
    x-default: 0
    x-prepare: false
    x-readable: true
    x-savable: true
    x-writable: true
    summary: "If true, SMP authentication will be required before accessing any SMP services. If false, all SMP services are available regardless of authentication status."
  - name: gw_smp_auth_req
    required: true
    schema:
      maximum: 1
      minimum: 0
      type: integer
    x-ctype: bool
    x-broadcast: true
    x-default: 0
    x-prepare: false
    x-readable: true
    x-savable: true
    x-writable: true
    summary: "If true, the gateway will require peripherals to authenticate before sending SMP messages"
  - name: smp_auth_timeout
    required: true
    schema:
      maximum: 86400
      minimum: 0
      type: integer
    x-ctype: uint32_t
    x-broadcast: true
    x-default: 300
    x-prepare: false
    x-readable: true
    x-savable: true
    x-writable: true
    summary: "SMP authentication will time out after a lapse in SMP commands lasting this number of seconds."
  - name: dm_cnx_retries
    summary: "Failed connection retries"
    description: "The number of times to retry a failed DM connection before going into backoff mode."
    required: true
    schema:
      type: integer
      minimum: 1
      maximum: 255
    x-ctype: uint8_t
    x-default: 3
    x-readable: true
    x-savable: true
    x-writable: true
  - name: dm_cnx_backoff_multi
    summary: "Connection backoff multiplier"
    description: "When in backoff mode, this multiplier will be applied to dm_cnx_delay for each connection retry."
    required: true
    schema:
      type: number
      minimum: 1.0
      maximum: 50.0
    x-ctype: float
    x-default: 2.0
    x-readable: true
    x-savable: true
    x-writable: true
  - name: dm_cnx_backoff_retries
    summary: "Connection backoff retries"
    description: "The number of times to retry a failed DM connection in backoff mode."
    required: true
    schema:
      type: integer
      minimum: 1
      maximum: 255
    x-ctype: uint8_t
    x-default: 5
    x-readable: true
    x-savable: true
    x-writable: true
